-- Add new fields to events table
ALTER TABLE events ADD COLUMN IF NOT EXISTS external_source VARCHAR(100);
ALTER TABLE events ADD COLUMN IF NOT EXISTS external_id VARCHAR(255);
ALTER TABLE events ADD COLUMN IF NOT EXISTS artist_name VARCHAR(255);
ALTER TABLE events ADD COLUMN IF NOT EXISTS language VARCHAR(100);
ALTER TABLE events ADD COLUMN IF NOT EXISTS genre VARCHAR(100);
