spring:
  application:
    name: eventora
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 516615796065-9thjqd0dp4ed70147m837jkjtbhl5b4o.apps.googleusercontent.com
            client-secret: ${GOOGLE_CLIENT_SECRET:YOUR_REAL_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-disabled: false
    clean-on-validation-error: true

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  secret: your_super_secret_jwt_key_which_should_be_long
  expiration: 86400000

razorpay:
  key-id: ${RAZORPAY_KEY_ID:fake_id}
  key-secret: ${RAZORPAY_KEY_SECRET:fake_secret}

server:
  port: 8080
